name: Scrape and Update Appwrite

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run scraping script
      env:
        APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
        APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}
        APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
        APPWRITE_DATABASE_ID: ${{ secrets.APPWRITE_DATABASE_ID }}
        APPWRITE_QUIZZES_COLLECTION_ID: ${{ secrets.APPWRITE_QUIZZES_COLLECTION_ID }}
        APPWRITE_TEST_SERIES_COLLECTION_ID: ${{ secrets.APPWRITE_TEST_SERIES_COLLECTION_ID }}
      run: python scrape_data.py
